# Dockerfile.backend
FROM python:3.10

WORKDIR /app

COPY backend/requirements.txt ./
RUN pip install -r requirements.txt

COPY backend/ app
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]

EXPOSE 5001

