
services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    volumes:
      - ../backend:/app
      - ../data:/data
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
